### ISSUE TITLE
Problems with MKMap and Cluster

### ISSUE THREAD

**Issue by ppamorim** [PureLayout/PureLayout#102]
Hi friends.
I recorded a video to show what`s happens here (click to open):

[![Hi](http://img.youtube.com/vi/HjBh3lgv3Vo/0.jpg)](https://www.youtube.com/watch?v=HjBh3lgv3Vo)

I think it\`s a problem with PureLayout because this happens with 2 libraries (of cluster, of course). Sorry if I`m wrong.

[ABFRealmMapView](https://github.com/bigfish24/ABFRealmMapView)
[KingPin](https://github.com/itsbonczek/kingpin)

I created a sample to represent this problem: [Fun-With-Swift](https://github.com/ppamorim/Fun-with-Swift/blob/master/Fun%20With%20Swift/ABFRealmMapView.swift)

**Comment by blueraz0r** [comment]
If these lines are your only constraints, then you are only specifying the width & height of the map view:
https://github.com/ppamorim/Fun-with-Swift/blob/master/Fun%20With%20Swift/ABFRealmMapView.swift#L51-L52

You also need to specify its position otherwise it is ambiguous and could change at runtime. That might be what you're seeing. Try also centering the map view in its superview?

**Comment by ppamorim** [comment]
```realmMapView.autoCenterInSuperview()``` worked! Thanks for the help.
