### ISSUE TITLE
Why do we install constraints in updateConstraints/updateViewConstraints?

### ISSUE THREAD

**Issue by Ricardo1980** [PureLayout/PureLayout#159]
Hello!
I'm just curious. Why does the tips document say that we should install the constraints in updateConstraints or updateViewConstraints rather than install the constraints at initialisation (so we avoid using the didSetupConstraints flag)?
I do that and it is working properly everything.

Am I missing something?

Thanks a lot.

**Comment by mhillebrand** [comment]
Because there are times when you want to _update_ constraints rather than simply creating them once and forgetting about them. With the `didSetupConstraints` Boolean, you can divide the update method into two chunks: one for creating and one for updating, which is nice because if you try to create the same constraint twice, your app will crash.

For example, half way through a user's session, you might want to tweak the constant of a constraint that's saved as a property, and then you'd call `view.setNeedsUpdateConstraints()`, which would tell the system to invoke `updateConstraints()` or `updateViewConstraints()`, depending on whether you're in a view or a view controller, respectively.

**Comment by Ricardo1980** [comment]
Thanks for reply. 
What about the case where you hace a simple and static UI? Is that flag redundant in this case?
Thanks.

**Comment by mhillebrand** [comment]
In that case, you could just add constraints right after you call `addSubview()` without overriding `updateConstraints()` or `updateViewConstraints()`, but having one of those update methods without the Boolean check is dangerous because they can get called more than once and crash your app due to duplicate constraints.
