### ISSUE TITLE
Expand API for swift

### ISSUE THREAD

**Issue by ConfusedVorlon** [PureLayout/PureLayout#161]
the swift grammar would allow for a more flexible PureLayout API by using default values

e.g. 

`func autoPinEdgesToSuperviewEdges(withInsets:ALEdgeInsets = .zero, excludingEdge:ALEdge = .none)() -> LayoutConstraint`

this would implicitly give 

`func autoPinEdgesToSuperviewEdges(excludingEdge:.top)`

which is a small, but nice refinement on the current need to always specify an inset

I'd be happy to do some work getting this started. 

I imagine it would be delivered as a subspec which updates the API for swift users (so that swift code would remain purely optional).

what are your thoughts? Would this be something you'd like to see?

**Comment by mickeyreiss** [comment]
Thanks for taking the time to write this up. I think this is an interesting suggestion. My only hesitation (like the other open PRs/issues) is that I don't have the opportunity to validate these changes personally anymore. If there is demand for the library to progress and keep up with Swift, I'd love to see it live on. I'll need some help to make this happen. Otherwise, unfortunately I tend to favor stability over change.

**Comment by ConfusedVorlon** [comment]
fair enough - I'll hold off then.

for what it's worth, I really like the library and use it in all my apps. I hope it lives on.

**Comment by mickeyreiss** [comment]
> for what it's worth, I really like the library and use it in all my apps. I hope it lives on.

Great to hear. Thanks for feedback! Let me know if you have any ideas for managing the library better.
