### ISSUE TITLE
iPhone X ???

### ISSUE THREAD

**Issue by qq756585379** [PureLayout/PureLayout#207]
when match iPhone X?

**Comment by evermeer** [comment]
Pull request is open for quite some time: https://github.com/PureLayout/PureLayout/pull/203

**Comment by toohotz** [comment]
Also made some fixes on the PR but neither the author nor the folks at are maintaining the repo have gotten back to it but in case you need it here's my fork that contains the fixes.

https://github.com/toohotz/PureLayout/tree/safearea

**Comment by andrewfashion** [comment]
Awesome thanks toohotz!

**Comment by yakushevichsv** [comment]
Hello, 
Any updates? 

@toohotz Thank you, but it is a fork on fork. 
Why not to create a fork from original repository ? )

**Comment by toohotz** [comment]
Hey @yakushevichsv the reason being is that I @himaratsu had made the original PR and I forked off of his fork to commit some fixes for his PR on the actual repo here.  My PR is supposed to go into his on his fork so that if / when he pulls it in, it would update the PR here on the repo.  Wanted to avoid having to make a duplicate PR but he has not responded in sometime to pull in the changes so I suppose if we prefer to clean up the forks, I can make a new PR here that contains our work together in a single PR.

**Comment by lwdupont** [comment]
Stay tuned, hope to release this on the weekend.
