### ISSUE TITLE
UITableViewCell doesn't use autolayout height when using insert cell into table

### ISSUE THREAD

**Issue by abbood** [PureLayout/PureLayout#234]
# Background
I use purelayout to programmatically create my UITableViewCells, following the instructions [here][1], which basically states that you gotta set the top/bottom constraints on a cell, then use 

    self.tableView.rowHeight = UITableViewAutomaticDimension;

to get it right:

[![enter image description here][2]][2]

# Problem
Everything works fine, except when I insert a new row into a tableView. I get this effect: https://youtu.be/eTGWsxwDAdk

To explain: as soon as I click on one of the tip cells, the table is supposed to insert a *driver tip* row. However you'll notice that wen i refresh the section (by clicking on a tip box), all the cells height inexplicably increases, but when i click on tip boxes again, they go back to their normal height
this is done with this code

    self.tableView.beginUpdates()
    self.tableView.reloadSections(IndexSet(integer:1), with: .automatic)
    self.tableView.endUpdates()

this is the implementation of the cellfor row

    // init table
    self.tableView.register(OrderChargeTableViewCell.self,
                                forCellReuseIdentifier: OrderChargeTableViewCell.regularCellIdentifier)
    self.tableView.register(OrderChargeTableViewCell.self,
                                forCellReuseIdentifier: OrderChargeTableViewCell.boldCellIdentifier)
        
    self.tableView.estimatedRowHeight = 25
    self.tableView.rowHeight = UITableViewAutomaticDimension

    public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        var cell: OrderChargeTableViewCell?
        if (indexPath.row == filteredModel.count-1) {
            cell = tableView.dequeueReusableCell(withIdentifier: OrderChargeTableViewCell.boldCellIdentifier,
                                                 for: indexPath) as? OrderChargeTableViewCell
        } else if (indexPath.row < filteredModel.count) {
            cell = tableView.dequeueReusableCell(withIdentifier: OrderChargeTableViewCell.regularCellIdentifier,
                                                 for: indexPath) as? OrderChargeTableViewCell
        }

        // add data to cell labels
        return cell!
    }

and this is the code for the UITableViewCell itself:

final class OrderChargeTableViewCell: UITableViewCell {

    // MARK: - init
    static let boldCellIdentifier = "TTOrderDetailBoldTableViewCell"
    static let regularCellIdentifier = "TTOrderDetailRegularTableViewCell"
    
    private var didSetupConstraints = false
    .. 
    
    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        
        self.keyLabel = TTRLabel()
        self.valueLabel = TTRLabel()

        if (reuseIdentifier == OrderChargeTableViewCell.regularCellIdentifier) {
            self.isCellStyleBold = false
        } else if (reuseIdentifier == OrderChargeTableViewCell.boldCellIdentifier) {
            self.isCellStyleBold = true
        } else {
            self.isCellStyleBold = false
            assertionFailure( "Attempt to create an OrderCharge cell with the wrong cell identifier: \(String(describing: reuseIdentifier))")
        }
        
        super.init(style: style, reuseIdentifier: reuseIdentifier)

        contentView.addSubview(keyLabel)
        contentView.addSubview(valueLabel)
        
    }

    override func updateConstraints()
    {
        if !didSetupConstraints {
            if (isCellStyleBold) {
                self.applyBoldFormatting()
            } else {
                self.applyRegularFormatting()
            }

            didSetupConstraints = true
        }
        
        super.updateConstraints()
    }
    public func applyBoldFormatting() {
        keyLabel.font = .ttrSubTitle
        valueLabel.font = .ttrBody
        
        keyLabel.autoPinEdge(.leading, to: .leading, of: contentView, withOffset: 15)
        keyLabel.autoAlignAxis(.vertical, toSameAxisOf: contentView)
        
        keyLabel.autoPinEdge(.top, to: .top, of: contentView, withOffset: 8)
        keyLabel.autoPinEdge(.bottom, to: .bottom, of: contentView, withOffset: -8)
        
        valueLabel.autoPinEdge(.trailing, to: .trailing, of: contentView, withOffset: -15)
        valueLabel.autoAlignAxis(.baseline, toSameAxisOf: keyLabel)
    }
    
    public func applyRegularFormatting() {
        keyLabel.font = .ttrCaptions
        valueLabel.font = TTRFont.Style.standard(.h3).value

        keyLabel.autoPinEdge(.leading, to: .leading, of: contentView, withOffset: 15)
        keyLabel.autoAlignAxis(.vertical, toSameAxisOf: contentView)
        
        keyLabel.autoPinEdge(.top, to: .top, of: contentView, withOffset: 6)
        keyLabel.autoPinEdge(.bottom, to: .bottom, of: contentView, withOffset: -4)
        
        valueLabel.autoPinEdge(.trailing, to: .trailing, of: contentView, withOffset: -15)
        valueLabel.autoAlignAxis(.baseline, toSameAxisOf: keyLabel)
    }
    

the driver tip row that gets inserted has the standard 44 pixel height of a cell:
[![enter image description here][3]][3]

whereas the other (properly formatted) cells have the 25 height:
[![enter image description here][4]][4]

  [1]: https://stackoverflow.com/a/18746930/766570
  [2]: https://i.stack.imgur.com/CTUPi.png
  [3]: https://i.stack.imgur.com/xRYUf.png
  [4]: https://i.stack.imgur.com/rPVhR.png

**Comment by lwdupont** [comment]
Hmm.. is it possible you are setting the constraints on the cell multiple times? It's hard to tell from the code when everything is being called. Code looks pretty good to me though.

**Comment by lwdupont** [comment]
Although the one thing I've had to do recently with tableview cells (because I'm embedding a UIView inside of it), is to set a height constraint on a base view, and embed everything else into that. I know not quite what you are doing, but I wonder if it might cause you some thoughts in your code? 

I've also had a coworker say he's been having issues with self sizing table views, and suggested that approach.

**Comment by toohotz** [comment]
A bit late to the party on this one but I've been meaning to give this a go and see what was happening for you.  This may / may not workout but just wanted to look into why your constraints were set the way they were and could be a solution to the inaccurate sized cell on insertion.

I decided to mockup your constraints in a .xib file for visual clarity and to then look at it as the size of the encapsulating view around it changes height.

The examples will use different number heights just for the sake of showing what happens to the labels as their superview's height changes.

In this first one here, I can see your ideal layout based upon the constraints that you have set

![Imgur](https://i.imgur.com/ud0IpX6.png)

When I resize it a bit to make the view larger that's when I see the possibly _unintended_ effect of the top and bottom constraints' relationship properties being equal.

![Imgur](https://i.imgur.com/nc8QtOw.png)

With that in mind I decided to redo the constraints the way in which I would have thought of doing so.  I wasn't sure if you intended on the `valueLabel` always being centered with the `keyLabel` but I made that assumption and aligned the `keyLabel`'s vertical axis to that of the `valueLabel`.  If you of course intended to have it aligned via its baseline you could keep that constraint the way it is.  The main thing that I did differently was for your top and bottom constraints, I made the `NSLayoutRelation` property set to `.greaterThanOrEqual` that way it pushes the top and bottom away as the view around it resizes.  I also opted to add constraint in between the two labels giving them a padding of at least 15 with the same `.greaterThanOrEqual` relational constraint for sanity sake so that your labels were ever long enough, they wouldn't run into each other.

The result at the default height of 44 looked like this

![Imgur](https://i.imgur.com/vF3SkyK.png)

And doubled to 88 it would look like this if the view were to be larger
![Imgur](https://i.imgur.com/5C2FZjO.png)

Feel free to let me know how this works out for you if you were still having issues though given the time this was originally opened I feel you might have solved it already 😕
