### ISSUE TITLE
Crash on iOS 13 (BETA)

### ISSUE THREAD

**Issue by SergejLogis** [PureLayout/PureLayout#240]
Since the release of iOS 13 BETA to the public, we started to get crash reports for one of our classes in the `updateConstraints()` method:

```
Fatal Exception: NSInvalidArgumentException
NSLayoutConstraint for <_UITableViewHeaderFooterViewLabel: 0x10c877500; frame = (0 0; 0 0); text = 'ПРОФИЛЬ'; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x281336490>>: A multiplier of 0 or a nil second item together with a location for the first attribute creates an illegal constraint of a location equal to a constant. Location attributes must be specified in pairs.
```

The offending line of code is:
`textLabel.autoPinEdge(toSuperviewEdge: .left, withInset: textLabelInsets.left)`
where `textLabelInsets` is `UIEdgeInsets`.
It never crashed previously.

**Comment by lwdupont** [comment]
I'll have a poke around in the next few days, but iOS 13 hasn't been released to the public yet, only developers. Apple's stated this first build is very unstable (hence the iTunes only restore this time). In past releases like this crashes like this have been fixed by Apple. So I'd be patient a bit.

**Comment by SergejLogis** [comment]
Totally agree with you! I just wanted to let you know, just in case 🤓And thanks for the quick reply!
